// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PROYECTO_GYM_MASTER.Data;

#nullable disable

namespace PROYECTO_GYM_MASTER.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260605225655_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PROYECTO_GYM_MASTER.Models.Ejercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("GrupoMuscular")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("Ejercicios");
                });

            modelBuilder.Entity("PROYECTO_GYM_MASTER.Models.Entrenador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Entrenadores");
                });

            modelBuilder.Entity("PROYECTO_GYM_MASTER.Models.Progreso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Altura")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double>("Peso")
                        .HasColumnType("double precision");

                    b.Property<double>("PorcentajeGrasa")
                        .HasColumnType("double precision");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Progresos");
                });

            modelBuilder.Entity("PROYECTO_GYM_MASTER.Models.Rutina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DuracionSemanas")
                        .HasColumnType("integer");

                    b.Property<int>("EntrenadorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EntrenadorId");

                    b.ToTable("Rutinas");
                });

            modelBuilder.Entity("PROYECTO_GYM_MASTER.Models.RutinaAsignada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RutinaId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RutinaId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("RutinasAsignadas");
                });

            modelBuilder.Entity("PROYECTO_GYM_MASTER.Models.RutinaEjercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DescansoSegundos")
                        .HasColumnType("integer");

                    b.Property<string>("Dia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EjercicioId")
                        .HasColumnType("integer");

                    b.Property<int>("Repeticiones")
                        .HasColumnType("integer");

                    b.Property<int>("RutinaId")
                        .HasColumnType("integer");

                    b.Property<int>("Series")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EjercicioId");

                    b.HasIndex("RutinaId");

                    b.ToTable("RutinaEjercicios");
                });

            modelBuilder.Entity("PROYECTO_GYM_MASTER.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PROYECTO_GYM_MASTER.Models.Entrenador", b =>
                {
                    b.HasOne("PROYECTO_GYM_MASTER.Models.Usuario", "Usuario")
                        .WithOne()
                        .HasForeignKey("PROYECTO_GYM_MASTER.Models.Entrenador", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PROYECTO_GYM_MASTER.Models.Progreso", b =>
                {
                    b.HasOne("PROYECTO_GYM_MASTER.Models.Usuario", "Usuario")
                        .WithMany("Progresos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PROYECTO_GYM_MASTER.Models.Rutina", b =>
                {
                    b.HasOne("PROYECTO_GYM_MASTER.Models.Entrenador", "Entrenador")
                        .WithMany("Rutinas")
                        .HasForeignKey("EntrenadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entrenador");
                });

            modelBuilder.Entity("PROYECTO_GYM_MASTER.Models.RutinaAsignada", b =>
                {
                    b.HasOne("PROYECTO_GYM_MASTER.Models.Rutina", "Rutina")
                        .WithMany("RutinasAsignadas")
                        .HasForeignKey("RutinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROYECTO_GYM_MASTER.Models.Usuario", "Usuario")
                        .WithOne("RutinaAsignada")
                        .HasForeignKey("PROYECTO_GYM_MASTER.Models.RutinaAsignada", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rutina");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PROYECTO_GYM_MASTER.Models.RutinaEjercicio", b =>
                {
                    b.HasOne("PROYECTO_GYM_MASTER.Models.Ejercicio", "Ejercicio")
                        .WithMany("RutinaEjercicios")
                        .HasForeignKey("EjercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROYECTO_GYM_MASTER.Models.Rutina", "Rutina")
                        .WithMany("RutinaEjercicios")
                        .HasForeignKey("RutinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ejercicio");

                    b.Navigation("Rutina");
                });

            modelBuilder.Entity("PROYECTO_GYM_MASTER.Models.Ejercicio", b =>
                {
                    b.Navigation("RutinaEjercicios");
                });

            modelBuilder.Entity("PROYECTO_GYM_MASTER.Models.Entrenador", b =>
                {
                    b.Navigation("Rutinas");
                });

            modelBuilder.Entity("PROYECTO_GYM_MASTER.Models.Rutina", b =>
                {
                    b.Navigation("RutinaEjercicios");

                    b.Navigation("RutinasAsignadas");
                });

            modelBuilder.Entity("PROYECTO_GYM_MASTER.Models.Usuario", b =>
                {
                    b.Navigation("Progresos");

                    b.Navigation("RutinaAsignada");
                });
#pragma warning restore 612, 618
        }
    }
}
